app_usuarios/urls.py
from django.urls import path
from .views import UsuarioListView, generar_reporte_csv, generar_reporte_xlsx

app_name = 'usuarios'

urlpatterns = [
    path('listar/', UsuarioListView.as_view(), name='listar'),
    path('reporte-csv/', generar_reporte_csv, name='reporte_csv'),
    path('reporte-xlsx/', generar_reporte_xlsx, name='reporte_xlsx'),
]

capresca/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter

from app_dashboard.views import dashboard_view
from app_funciones.views import (
     vista_sin_autenticar, 
     vista_requiere_autenticacion, 
     modelo_listado )
from app_clases.views import ( 
    SinAutenticarView, 
    ConAutenticacionView, 
    ModelosListView )
from app_usuarios.api.views import UsuariosViewSet

# Defino el router para Usuario
router = DefaultRouter()
router.register('usuarios', UsuariosViewSet)



urlpatterns = [
    path('', dashboard_view, name='dashboard'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


    path('funciones/sin/', vista_sin_autenticar, name='vista_sin_autenticar'),
    path('funciones/con/', vista_requiere_autenticacion, name='vista_con_autenticacion'),
    path('funciones/list/', modelo_listado, name='funcion_listado'),

    path('clases/sin/', SinAutenticarView.as_view(), name='clases_sin'),
    path('clases/con/', ConAutenticacionView.as_view(), name='clases_con'),
    path('clases/list/', ModelosListView.as_view(), name='clases_lista'),

    path('usuarios/', include('app_usuarios.urls', namespace='usuarios')),

    path('api/', include('app_clases.api.urls', namespace='api')),
    path('api2/', include('app_funciones.api.urls', namespace='api2')),

    # urls paths para el router
    path('api3/', include(router.urls)),
    path('poblar/', include('app_usuarios.api.urls')),

    path("admin/", admin.site.urls),


]


urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

templates/usuarios/lista.html
{% extends 'base.html' %}
{% load static %}

{# Imágenes de <a href="https://www.flaticon.es/iconos-gratis/formato" title="formato iconos">Formato iconos creados por Yuan Design - Flaticon</a> #}

{% block content %}
<div class="container">

    <ul class="nav nav-underline bg-success justify-content-center">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'usuarios:reporte_csv' %}">
            <img src="{% static 'extension-csv.png' %}" width="64" alt="extension-csv" />
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'usuarios:reporte_xlsx' %}">
            <img src="{% static 'extension-xls.png' %}" width="64" alt="extension-xls" />
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <img src="{% static 'extension-pdf.png' %}" width="64" alt="extension-pdf" />
          </a>
        </li>
      </ul>

<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Título</th>
        <th scope="col">Apellido</th>
        <th scope="col">Nombre</th>
        <th scope="col">Género</th>
        <th scope="col">Ciudad</th>
        <th scope="col">País</th>
        <th scope="col">e-mail</th>
      </tr>
    </thead>
    <tbody>
        {% for usuario in object_list %}
            <tr>
                <th scope="row">{{usuario.id}}</th>
                <td>{{usuario.titulo}}</td>
                <td>{{usuario.apellido}}</td>
                <td>{{usuario.nombre}}</td>
                <td>{{usuario.genero}}</td>
                <td>{{usuario.ciudad}}</td>
                <td>{{usuario.pais}}</td>
                <td>{{usuario.email}}</td>
            </tr>
        {% endfor %}
    </tbody>
  </table>

  <div class="container" style="text-align: center;">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; primera</a>
            <a href="?page={{ page_obj.previous_page_number }}">anterior</a>
        {% endif %}

        <span class="current">
            Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">siguiente</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">última &raquo;</a>
        {% endif %}
    </span>
  </div>

</div>

{% endblock content %}