capresca/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter

from app_dashboard.views import dashboard_view
from app_funciones.views import (
     vista_sin_autenticar, 
     vista_requiere_autenticacion, 
     modelo_listado )
from app_clases.views import ( 
    SinAutenticarView, 
    ConAutenticacionView, 
    ModelosListView )
from app_usuarios.api.views import UsuariosViewSet

# Defino el router para Usuario
router = DefaultRouter()
router.register('usuarios', UsuariosViewSet)



urlpatterns = [
    path('', dashboard_view, name='dashboard'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


    path('funciones/sin/', vista_sin_autenticar, name='vista_sin_autenticar'),
    path('funciones/con/', vista_requiere_autenticacion, name='vista_con_autenticacion'),
    path('funciones/list/', modelo_listado, name='funcion_listado'),

    path('clases/sin/', SinAutenticarView.as_view(), name='clases_sin'),
    path('clases/con/', ConAutenticacionView.as_view(), name='clases_con'),
    path('clases/list/', ModelosListView.as_view(), name='clases_lista'),

    path('usuarios/', include('app_usuarios.urls', namespace='usuarios')),

    path('api/', include('app_clases.api.urls', namespace='api')),
    path('api2/', include('app_funciones.api.urls', namespace='api2')),

    # urls paths para el router
    path('api3/', include(router.urls)),
    path('poblar/', include('app_usuarios.api.urls')),

    path("admin/", admin.site.urls),


]


urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

app_clases/models.py
from django.db import models

# Create your models here.
class ModeloPruebaParaClases(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=100)
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)

app_funciones/models.py
from django.db import models

# Create your models here.
class ModeloPruebaParaFunciones(models.Model):
    marca = models.CharField(max_length=50)
    anio = models.PositiveIntegerField()
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django Capresca</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>

    

    {% if user.is_authenticated %}
        Bienvenido <strong>{{ user.username }}</strong>
        para Desconectarse, <a href="{% url 'logout' %}"> click aquí</a>
    {% else %}
        Para Loguearse, <a href="{% url 'login' %}"> click aquí</a>
    {% endif %}


    {% block content %}
    {% endblock content %}




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

templates/con_autenticacion.html
{% extends 'base.html' %}

{% block content %}

<h1>SOLO USUARIOS AUTENTICADOS</h1>

{% endblock content %}

templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
<h1>PÁGINA PRINCIPAL DE LA APLICACIÓN</h1>

{% if perms.app_clases %}
    <h3>Tiene permisos para acceder a las opciones de la App Clases</h3>

    {% if perms.app_clases.view_modelopruebaparaclases %}
        <h4>Puede Ver / Listar</h4>
    {% endif %}

    {% if perms.app_clases.add_modelopruebaparaclases %}
        <h4>Puede agregar</h4>
    {% endif %}

    {% if perms.app_clases.change_modelopruebaparaclases %}
        <h4>Puede cambiar</h4>
    {% endif %}

    {% if perms.app_clases.delete_modelopruebaparaclases %}
        <h4>Puede borrar</h4>
    {% endif %}

{% endif %}

{% if perms.app_funciones %}

    <div class="card" style="width: 18rem;">
        <div class="card-header">
            <h3>Tiene permisos para acceder a las opciones de la App Funciones</h3>
        </div>
        <ul class="list-group list-group-flush">
        <li class="list-group-item">
            {% if perms.app_funciones.view_modelopruebaparafunciones %}
                <a href="{% url 'vista_con_autenticacion' %}">Vista con Autenticacion</a>
            {% endif %}
        </li>
        <li class="list-group-item">
            {% if perms.app_funciones.add_modelopruebaparafunciones %}
            <h4>Puede agregar</h4>

            {% endif %}
        </li>

        <li class="list-group-item">
            {% if perms.app_funciones.delete_modelopruebaparafunciones %}
            <h4>Puede borrar</h4>
        {% endif %}
        </li>
        </ul>
    </div>




    

  
    






{% endif %}

{% endblock content %}

templates/lista.html
{% extends 'base.html' %}

{% block content %}

<ul>
{% for object in object_list %}
    <li>{{object}}</li>
{% endfor %}

</ul>
{% endblock content %}

templates/sin_autenticacion.html
{% extends 'base.html' %}

{% block content %}

<h1>PUEDEN ACCEDER TODOS!</h1>

{% endblock content %}